version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.PUSH_TOKEN }}
updates:
  - package-ecosystem: npm
    registries:
      - npm-github
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(deps-dev)'
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'eslint'
